### PR TITLE
server: Add unit tests from Diffblue Deeptest

### PR DESCRIPTION
**Pull request by petersear**
Pre-PR review request:

Existing coverage:      42.15%
Increase in coverage: 15.84%
Verfied tests:               2467
Tests for PR:                   15

### CODE REVIEW

**Review by JohnLBergqvist — CHANGES_REQUESTED** [review]
References to deeptestutils & java.lang.reflect are unnecessary as none of the tests use reflection. Aside from that, it's all fine.

**Comment by paulkennethkent** [comment]
👍 They are great! Add the licence and commit using difflbue-assistant + John suggestions and you are good to go.

**Review by paulkennethkent — APPROVED** [review]

**Comment by sudo-jaa** [comment]
Agreed with John about the DeeptestUtils, but other than that they're gawjus tests :kiss:

**Review by sudo-jaa — APPROVED** [review]

**Comment by petersear** [comment]
Thanks for the comments. All changes made and pushed.
Will file PR.

**Pull request closed without merging**
